theme: null  # Disables Jekyll theme processing
exclude:
  - README.md
  - LICENSE
  - node_modules
remote_theme: pages-themes/time-machine@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: [Violet's Portfolio]
